apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-class
  namespace: mynamespace
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuname: StandardSSD_LRS
